"""Limits shared by authoritative checkout and the hosted payment adapter."""

HOSTED_CHECKOUT_MIN_AMOUNT_CENTS = 50
HOSTED_CHECKOUT_MAX_AMOUNT_CENTS = 99_999_999
HOSTED_CHECKOUT_SESSION_TTL_SECONDS = 2 * 60 * 60
UNLINKED_PAYMENT_RESERVATION_TTL_SECONDS = 3 * 60 * 60
FAILED_PAYMENT_RETRY_WINDOW_SECONDS = 24 * 60 * 60
PAYMENT_RESERVATION_SWEEP_INTERVAL_SECONDS = 5 * 60
